export enum PRIORITY_QUEUE_PRIORITIES {
  // highest priority
  'PRIORITY_BAN_USER' = 'PRIORITY_BAN_USER',
  'PRIORITY_GAME_INPUT' = 'PRIORITY_GAME_INPUT',
  'PRIORITY_IMAGE' = 'PRIORITY_IMAGE',
  'PRIORITY_PUBSUB_EVENTS_QUEUE' = 'PRIORITY_PUBSUB_EVENTS_QUEUE',
  'PRIORITY_MIC_INPUT' = 'PRIORITY_MIC_INPUT',
  'PRIORITY_COLLAB_MIC_INPUT' = 'PRIORITY_COLLAB_MIC_INPUT',
  'PRIORITY_REMIND_ME' = 'PRIORITY_REMIND_ME',
  'PRIORITY_TWITCH_CHAT_QUEUE' = 'PRIORITY_TWITCH_CHAT_QUEUE',
  // lowest priority
}
