VTS_EXPRESSIONS = {
  'FLUSHED': 'f4',
  'ANGRY': 'f9',
  'SAD': 'f7',
  'BROWN_HAIR': 'f11'
}

AZURE_SPEAKING_STYLE_TAGS = {
  'WHISPERING': '<WHISPERING>'
}

TWITCH_EVENTS = {
  'BAN': 'BAN',
  'SUB': 'SUB',
  'BITS': 'BITS'
}

PRIORITY_QUEUE_PRIORITY_MAP = {
  # highest priority
  'PRIORITY_BAN_USER': 1,
  'PRIORITY_GAME_INPUT': 2,
  'PRIORITY_IMAGE': 3,
  'PRIORITY_PUBSUB_EVENTS_QUEUE': 4,
  'PRIORITY_MIC_INPUT': 5,
  'PRIORITY_COLLAB_MIC_INPUT': 6,
  'PRIORITY_TWITCH_CHAT_QUEUE': 7,
  # lowest priority
}

PRIORITY_QUEUE_PRIORITIES = {
  # highest priority
  'PRIORITY_BAN_USER': 'PRIORITY_BAN_USER',
  'PRIORITY_GAME_INPUT': 'PRIORITY_GAME_INPUT',
  'PRIORITY_IMAGE': 'PRIORITY_IMAGE',
  'PRIORITY_PUBSUB_EVENTS_QUEUE': 'PRIORITY_PUBSUB_EVENTS_QUEUE',
  'PRIORITY_MIC_INPUT': 'PRIORITY_MIC_INPUT',
  'PRIORITY_COLLAB_MIC_INPUT': 'PRIORITY_COLLAB_MIC_INPUT',
  'PRIORITY_TWITCH_CHAT_QUEUE': 'PRIORITY_TWITCH_CHAT_QUEUE',
  # lowest priority
}
