from constants import banned_twitch_keywords
import re

# generated by chatgpt
def find_banned_words(sentence):
  # Create a regex pattern to match any banned word as a whole word
  pattern = r'\b(' + '|'.join(map(re.escape, banned_twitch_keywords)) + r')\b'
    
  # Find all occurrences of banned words in the sentence
  matches = re.findall(pattern, sentence, re.IGNORECASE)
    
  # Return the list of matched banned words (remove duplicates if needed)
  return list(set(matches))
