import re
import emoji
from gen_edited_luna_response import punctuation_characters

def remove_text_inside_parentheses(s):
  # this function was generated by ChatGPT
  # The regex pattern here says to find anything that starts with "(" 
  # and ends with ")" and remove it.
  return re.sub(r'\(.*?\)', '', s).strip()

def move_emojis_to_end(s):
  # move emojis to end of response, to avoid subtitles getting out of sync
  emojis = ''
  text_without_emojis = ''
  for i in s.strip():
    try:
      if i in emoji.EMOJI_DATA:
        emojis += i
      else:
        text_without_emojis += i
    except:
      text_without_emojis += i
  text_with_emojis_moved_to_end = f'{text_without_emojis} {emojis}'
  # removing an emoji can leave an unwanted space before certain punctuation. let's clean that up.
  replacements = [
    (' ,', ','),
    (' .', '.'),
    (' ?', '?'),
    (' !', '!'),
    (' }', '}'),
    (' )', ')'),
    (' ]', ']'),
    (' ;', ';'),
    (' :', ':'),
    ('  ', ' '),
  ]
  for old, new in replacements:
    text_with_emojis_moved_to_end = text_with_emojis_moved_to_end.replace(old, new)
  return text_with_emojis_moved_to_end.strip()

def does_one_word_start_with_at(strings):
  for string in strings:
    if string.startswith('@'):
      return True
  return False

def conditionally_add_period(s):
  if s[-1] not in punctuation_characters and s[-1] not in emoji.EMOJI_DATA:
    return f'{s}.' # get rid of weird sound bytes with say-as=message
  return s


if __name__ == '__main__':
  print(move_emojis_to_end('Foo. 🖤. Bar.'))
